version: '3.8'

services:
  hello-world-web:
    build: .
    ports:
      - "3000:3000"
    container_name: hello-world-site
    restart: unless-stopped
    
    # Uncomment the volumes below for live development
    # volumes:
    #   - ./index.html:/usr/share/nginx/html/index.html:ro
    #   - ./style.css:/usr/share/nginx/html/style.css:ro
    #   - ./script.js:/usr/share/nginx/html/script.js:ro 